### PR TITLE
Update k8s.io/legacy-cloud-providers to v0.26.1

### PR DESCRIPTION
**Pull request by ialidzhikov**
**Which issue(s) this PR fixes**:
Part of https://github.com/gardener/gardener/issues/6773

**Release note**:

```improvement operator
NONE
```

### CODE REVIEW

**Comment by ialidzhikov** [comment]
This PR will be obsolete if https://github.com/gardener/gardener-extension-provider-aws/pull/682 is merged meanwhile.

**Review by rfranzke — COMMENTED** [review]
Sorry for the delay. The changes as such look good. Let's go directly for 1.26.1 as it's already released.

**Review by rfranzke — APPROVED** [review]
/lgtm

**Pull request merged**
